name: Run Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  trigger-main-build:
    runs-on: ubuntu-latest
    container:
      image: node:20.11.1-alpine
    steps:
    - uses: actions/checkout@v3
      with:
        path: 'server'
        fetch-depth: 1

    - name: Install Dependencies
      working-directory: server
      run: npm ci

    - name: Run Tests
      working-directory: server
      run: npm run test
