name: Run Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  trigger-main-build:
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-node:1.0.7
    steps:
    - name: Clone
      run: |
        COMMIT_SHA="<commit-sha>"
        REPO_URL="https://dev.sp-tarkov.com/SPT-AKI/Server.git"

        rm -rf /workspace/SPT-AKI/Build/server
        git clone ${REPO_URL} --branch master /workspace/SPT-AKI/Build/server

        cd /workspace/SPT-AKI/Build/server
        git checkout ${COMMIT_SHA}
      shell: bash

    - name: Pull LFS Files
      run: |
        cd /workspace/SPT-AKI/Build/server
        git lfs pull
      shell: bash

    - name: Install NPM Dependencies
      run: |
        cd /workspace/SPT-AKI/Build/server
        npm install
      shell: bash

    - name: Run Tests
      run: |
        cd /workspace/SPT-AKI/Build/server
        npm run test
      shell: bash
